name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TERM: screen-256color

jobs:
  main:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: End to end testing
        run: make e2e
